### ISSUE TITLE
error running run-container.sh

### ISSUE THREAD

**Issue by fredericlepied** [test-network-function/test-network-function#170] opened 2021-04-28 06:14 UTC
I have this error when running run-container.sh
```
$ ./run-container.sh -t /var/tmp/dci_967dc0f0-b4f6-490b-b655-3a0e1967fc52_logs -o /tmp  diagnostic generic
-t /var/tmp/dci_967dc0f0-b4f6-490b-b655-3a0e1967fc52_logs
-o /tmp
Kubeconfig Autodiscovery: configuration loaded from $KUBECONFIG
Mounting 1 kubeconfig volume(s):
-v /home/dciteam/clusterconfigs-cluster6/kubeconfig:/usr/tnf/kubeconfig/config:ro
+ docker run --rm -v /home/dciteam/clusterconfigs-cluster6/kubeconfig:/usr/tnf/kubeconfig/config:ro -v /var/tmp/dci_967dc0f0-b4f6-490b-b655-3a0e1967fc52_logs:/usr/tnf/config -v /tmp:/usr/tnf/claim -e KUBECONFIG=/usr/tnf/kubeconfig/config quay.io/testnetworkfunction/test-network-function:latest ./run-cnf-suites.sh -o /usr/tnf/claim diagnostic generic
Running with focus 'generic|diagnostic'. Report will be output to '/usr/tnf/claim'
--- FAIL: TestTest (0.00s)
panic: 
Your test failed.
Ginkgo panics to prevent subsequent assertions from running.
Normally Ginkgo rescues this panic so you shouldn't see it.

But, if you make an assertion in a goroutine, Ginkgo can't capture the panic.
To circumvent this, you should call

	defer GinkgoRecover()

at the top of the goroutine that caused this panic.
 [recovered]
	panic: 
Your test failed.
Ginkgo panics to prevent subsequent assertions from running.
Normally Ginkgo rescues this panic so you shouldn't see it.

But, if you make an assertion in a goroutine, Ginkgo can't capture the panic.
To circumvent this, you should call

	defer GinkgoRecover()

at the top of the goroutine that caused this panic.


goroutine 4 [running]:
testing.tRunner.func1.1(0x9c2c00, 0xb6e8a0)
	/usr/lib/golang/src/testing/testing.go:999 +0x319
testing.tRunner.func1(0xc0001af680)
	/usr/lib/golang/src/testing/testing.go:1002 +0x402
panic(0x9c2c00, 0xb6e8a0)
	/usr/lib/golang/src/runtime/panic.go:969 +0x166
github.com/onsi/ginkgo.Fail(0xc0001fa580, 0xa3, 0xc0002d05b8, 0x1, 0x1)
	/usr/tnf/tnf-src/vendor/github.com/onsi/ginkgo/ginkgo_dsl.go:270 +0xc8
github.com/onsi/gomega/internal/assertion.(*Assertion).match(0xc0002da340, 0xb87c60, 0x1089e80, 0x1, 0x0, 0x0, 0x0, 0xc0002da340)
	/usr/tnf/tnf-src/vendor/github.com/onsi/gomega/internal/assertion/assertion.go:79 +0x20e
github.com/onsi/gomega/internal/assertion.(*Assertion).To(0xc0002da340, 0xb87c60, 0x1089e80, 0x0, 0x0, 0x0, 0x0)
	/usr/tnf/tnf-src/vendor/github.com/onsi/gomega/internal/assertion/assertion.go:38 +0xc7
github.com/test-network-function/test-network-function/test-network-function/generic.GetTestConfiguration(0xc00000fac0)
	/usr/tnf/tnf-src/test-network-function/generic/suite.go:241 +0xf6
github.com/test-network-function/test-network-function/test-network-function/generic.glob..func1()
	/usr/tnf/tnf-src/test-network-function/generic/suite.go:133 +0x7f
github.com/onsi/ginkgo/internal/suite.(*Suite).PushContainerNode(0xc0001e0070, 0xa9f33e, 0x7, 0xacdd78, 0x0, 0xf63eb5, 0x37, 0x82, 0xc00022c460, 0x9e)
	/usr/tnf/tnf-src/vendor/github.com/onsi/ginkgo/internal/suite/suite.go:181 +0x31e
github.com/onsi/ginkgo/internal/suite.(*Suite).Run(0xc0001e0070, 0x7f2ec0759260, 0xc0001af680, 0xaadcf8, 0x1c, 0xc00000fbc0, 0x2, 0x2, 0xb8bf20, 0xc0001b68c0, ...)
	/usr/tnf/tnf-src/vendor/github.com/onsi/ginkgo/internal/suite/suite.go:70 +0x19e
github.com/onsi/ginkgo.RunSpecsWithCustomReporters(0xb7d260, 0xc0001af680, 0xaadcf8, 0x1c, 0xc00000fba0, 0x2, 0x2, 0x2)
	/usr/tnf/tnf-src/vendor/github.com/onsi/ginkgo/ginkgo_dsl.go:229 +0x220
github.com/onsi/ginkgo.RunSpecsWithDefaultAndCustomReporters(0xb7d260, 0xc0001af680, 0xaadcf8, 0x1c, 0xc0002948e0, 0x1, 0x1, 0x1)
	/usr/tnf/tnf-src/vendor/github.com/onsi/ginkgo/ginkgo_dsl.go:217 +0xad
github.com/test-network-function/test-network-function/test-network-function.TestTest(0xc0001af680)
	/usr/tnf/tnf-src/test-network-function/suite_test.go:129 +0x2f9
testing.tRunner(0xc0001af680, 0xacdd28)
	/usr/lib/golang/src/testing/testing.go:1050 +0xdc
created by testing.(*T).Run
	/usr/lib/golang/src/testing/testing.go:1095 +0x28b
```

**Comment by ryandgoulding** [comment] 2021-04-28 12:55
Have you installed the test partner pod?

https://github.com/test-network-function/cnf-certification-test-partner/tree/main/test-partner

oc create -f namespace.yaml

oc create -f partner.yaml

**Comment by fredericlepied** [comment] 2021-04-28 19:21
> Have you installed the test partner pod?
> 
> https://github.com/test-network-function/cnf-certification-test-partner/tree/main/test-partner
> 
> oc create -f namespace.yaml
> 
> oc create -f partner.yaml

yes I have. how can I check that everything is correct?

**Comment by fredericlepied** [comment] 2021-04-29 11:23
Here is the output of `oc describe pod -n tnf partner`:
```
Name:         partner
Namespace:    tnf
Priority:     0
Node:         worker-2/192.168.62.22
Start Time:   Thu, 29 Apr 2021 05:52:16 -0500
Labels:       app=partner
Annotations:  k8s.ovn.org/pod-networks:
                {"default":{"ip_addresses":["10.130.2.43/23"],"mac_address":"0a:58:0a:82:02:2b","gateway_ips":["10.130.2.1"],"ip_address":"10.130.2.43/23"...
              k8s.v1.cni.cncf.io/network-status:
                [{
                    "name": "",
                    "interface": "eth0",
                    "ips": [
                        "10.130.2.43"
                    ],
                    "mac": "0a:58:0a:82:02:2b",
                    "default": true,
                    "dns": {}
                }]
              k8s.v1.cni.cncf.io/networks-status:
                [{
                    "name": "",
                    "interface": "eth0",
                    "ips": [
                        "10.130.2.43"
                    ],
                    "mac": "0a:58:0a:82:02:2b",
                    "default": true,
                    "dns": {}
                }]
              openshift.io/scc: privileged
Status:       Running
IP:           10.130.2.43
IPs:
  IP:  10.130.2.43
Containers:
  partner:
    Container ID:  cri-o://bed9118001aad3d70f613c5b44d861800936a4f3b07942a8cd2f54f256f65fda
    Image:         jumphost.cluster6.dfwt5g.lab:5000/testnetworkfunction/cnf-test-partner
    Image ID:      jumphost.cluster6.dfwt5g.lab:5000/testnetworkfunction/cnf-test-partner@sha256:5667e66df69078408f97f122238b7ac38d6ca621dab947ca3c46db926f6686a5
    Port:          <none>
    Host Port:     <none>
    Command:
      tail
      -f
      /dev/null
    State:          Running
      Started:      Thu, 29 Apr 2021 05:52:31 -0500
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     1
      memory:  1Gi
    Requests:
      cpu:        1
      memory:     1Gi
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-pb5wk (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  default-token-pb5wk:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-pb5wk
    Optional:    false
QoS Class:       Guaranteed
Node-Selectors:  role=partner
Tolerations:     node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason          Age   From               Message
  ----    ------          ----  ----               -------
  Normal  Scheduled       29m   default-scheduler  Successfully assigned tnf/partner to worker-2
  Normal  AddedInterface  29m   multus             Add eth0 [10.130.2.43/23]
  Normal  Pulling         29m   kubelet            Pulling image "jumphost.cluster6.dfwt5g.lab:5000/testnetworkfunction/cnf-test-partner"
  Normal  Pulled          29m   kubelet            Successfully pulled image "jumphost.cluster6.dfwt5g.lab:5000/testnetworkfunction/cnf-test-partner" in 13.008200801s
  Normal  Created         29m   kubelet            Created container partner
  Normal  Started         29m   kubelet            Started container partner
```

**Comment by ryandgoulding** [comment] 2021-04-29 18:01
@crwr45 are you aware of any reason this is happening?  I have reproduced this locally as well.

This seems like a real issue;  continuing to debug.

**Comment by crwr45** [comment] 2021-04-30 10:27
I have successfully run the container tags `latest`, `v1.0.6` and `v1.0.7` locally against my CodeReady Containers install, without error.
I was also able to reproduce this panic, by renaming, corrupting or removing the `generic_test_configuration.yml` file from the directory that contains the test configuration. That seems to be the root of the issue, but obfuscated by the Ginkgo panic suppressing the actual error message.

**Comment by crwr45** [comment] 2021-04-30 10:47
So to get the tests to run, you will need to change something about how the config file `generic_test_configuration.yml` is provided to the container.

We need to change how the error is trapped and reported. The current use of `gomega.Expect(err).To(gomega.BeNil())`, without a `defer GinkgoRecover()` preceding it causes the message to be suppressed and replaced with a generic Ginkgo message.
Finally, we should review the documentation of configuring and running the container to clarify anything missing around the process, and perhaps include a piece on debugging.

**Comment by fredericlepied** [comment] 2021-04-30 11:00
What do you mean by change something?

I run it like this:

```
$ ./run-container.sh -t /var/tmp/dci_f6d9ce21-9f82-44d2-aa52-8d4ad6e56088_logs -o /var/tmp/dci_f6d9ce21-9f82-44d2-aa52-8d4ad6e56088_logs diagnostic generic
```

what should I do?

**Comment by crwr45** [comment] 2021-04-30 11:24
From that command, the directory `/var/tmp/dci_f6d9ce21-9f82-44d2-aa52-8d4ad6e56088_logs` (the `-t` flag on `run-container.sh`) is mounted to `/usr/tnf/config` inside the container. The test suite then loads `/usr/tnf/config/generic_test_configuration.yml` inside the container (`/var/tmp/dci_f6d9ce21-9f82-44d2-aa52-8d4ad6e56088_logs/generic_test_configuration.yml` on the host) but the file is not being loaded successfully.
As I said above the actual error message is being suppressed due to a bug, so I can't say for sure at this point what the real error is hence the slightly vague "change something". It might be malformed YAML, an incorrect filename, permissions, or something else entirely.
We'll make a change to expose the true error, which will make diagnosing it easier, but until then you may be able to resolve the issue by double checking the current setup to see if there's something obvious preventing the config file being read.

**Comment by crwr45** [comment] 2021-04-30 16:45
@fredericlepied There is a new version of the image up that contains changes to how configuration loading errors are handled and some extra logging. Please can you re-run and report back with what it shows? Thanks

**Comment by fredericlepied** [comment] 2021-05-03 15:11
it is better as there is no back trace anymore.

**Comment by ryandgoulding** [comment] 2021-05-20 13:54
Do you know which version of `docker` was used when this issue was experienced?  I found upgrading to the latest version of `docker` fixed this problem for me locally.

**Comment by ryandgoulding** [comment] 2021-06-02 19:39
Hi @fredericlepied .  Can you confirm which version of `docker` was used?  There are known issues in older versions of `docker`.

**Comment by ryandgoulding** [comment] 2021-06-07 15:34
There has been no communication on this issue from the original contributor in over a month.  I am going to close this for now;  please feel free to re-open if the problem persists.

**Closed by ryandgoulding** 2021-06-07 15:34 UTC
