### ISSUE TITLE
Daemonset can not be scheduled by default-scheduler in the latest version on ocp 4.6 due to invalid configmap

### ISSUE THREAD

**Issue by kononovn** [test-network-function/test-network-function#415] opened 2021-10-27 17:54 UTC
daemonset can not be scheduled by default-scheduler in latest version on ocp4.6 due to invalid configmap, please check logs below:
Normal Scheduled 54s default-scheduler Successfully assigned default/debug-x9sz4 to qe-tnf-qe-xmrrb-worker-0-4t7kv 
Warning FailedMount 23s (x7 over 54s) kubelet MountVolume.SetUp failed for volume "kube-api-access-whppm" : [configmap "kube-root-ca.crt" not found, configmap "openshift-service-ca.crt" not found] certificate

**Comment by javierpena** [comment] 2021-12-03 10:45
I've been checking this issue, and it is caused by the definition of the debug partner pod in https://github.com/test-network-function/cnf-certification-test-partner/blob/main/test-partner/debugpartner.yaml#L71-L93 . This definition includes some certificates that are only present as configmaps since Kubernetes 1.20 (OpenShift 4.7) [1].

I think this volume definition is not actually needed, since the /run/secrets/kubernetes.io/serviceaccount mount is automatically done with the right data. It is probably there because it was extracted from a running pod.

[1] - https://bugzilla.redhat.com/show_bug.cgi?id=1916688

**Comment by javierpena** [comment] 2021-12-03 10:54
Should be fixed by https://github.com/test-network-function/cnf-certification-test-partner/pull/66

**Closed** 2021-12-13 17:32 UTC
